# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    env:
      API_KEY: "6c2262857eb848b6a1fad45a8a3f6686"
      PRIV_KEY1: "0e10373c761cbe50eafe9798cb8df4ed9edeb13c1396684daa0f8eefd6022abc"
      PRIV_KEY2: "29de3ab5d11acd8cf5fc3af89691e293cd0726b1f2e93a62e96560ec5eab0181"
      LOCAL_RUN: True
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'hardhat/package.json'
    
    - run: cd sdk; npm install
    - run: cd hardhat; npm install
    - run: cd hardhat; npm ci
    - run: cd hardhat; npm test
